"""
01_study1_eis_coherence.py
═══════════════════════════════════════════════════════════════════════════════
STUDY 1 — EIS Internal Coherence and Weight Stability  (COH design)

WHAT THIS IS:
  An INTERNAL construct check on the EIS operationalization. It characterizes the
  scoring function's own behavior. It does NOT claim that EIS discriminates
  rigorous from questionable research against any external ground truth — that
  question is addressed, against replication outcomes, in Study 4.

THREE ANALYSES:
  1. Dimensional non-redundancy
     Correlation matrix among the five EIS component scores across a corpus of
     synthetic protocols generated by varying the underlying protocol features
     INDEPENDENTLY. Any correlation in the OUTPUT components therefore reflects
     coupling induced by the scoring design (e.g. shared inputs), which is what
     a non-redundancy check is meant to surface.

  2. Weight stability
     EIS recomputed under several weighting schemes; rank-ordering of protocols
     compared across schemes via Spearman rank correlation. High stability means
     the composite is robust to reasonable weight choices.

  3. Synthetic monotonicity sanity check  (SECONDARY, CIRCULAR BY CONSTRUCTION)
     Protocols built to satisfy progressively more dimensions should score higher.
     This is labeled circular-by-construction and is NOT evidence of validity.

PROVENANCE:
  All component scores come from the canonical v3.0 engine via eis_wrapper.
  Master seed fixed. Outputs written to outputs/study1/ ; run logged to logs/.

NOT VALIDATION. Internal coherence only. External evidential burden rests on Study 4.
═══════════════════════════════════════════════════════════════════════════════
"""

import sys
import json
import platform
from pathlib import Path
from datetime import datetime

import numpy as np
import pandas as pd
from scipy import stats as scipy_stats

# --- import path: works both in code/+engine/ layout and in a flat dir ---
HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
sys.path.insert(0, str(HERE.parent / "engine"))

from eis_wrapper import ProtocolSpec, score_protocol, components_of  # noqa: E402

# --- master seed (declared in 00_environment_check.py) ---
MASTER_SEED = 20250805

# --- five component keys, in the order used throughout ---
COMPONENTS = ['preregistration', 'split_strength', 'protocol_adherence',
              'leakage_score', 'transparency']

# --- weighting schemes (each sums to 1.0); 'default' = v3.0 DEFAULT_WEIGHTS ---
WEIGHT_SCHEMES = {
    'default':               {'preregistration': 0.25, 'protocol_adherence': 0.25,
                              'split_strength': 0.20, 'leakage_risk': 0.15, 'transparency': 0.15},
    'equal':                 {'preregistration': 0.20, 'protocol_adherence': 0.20,
                              'split_strength': 0.20, 'leakage_risk': 0.20, 'transparency': 0.20},
    'preregistration_dom':   {'preregistration': 0.40, 'protocol_adherence': 0.15,
                              'split_strength': 0.15, 'leakage_risk': 0.15, 'transparency': 0.15},
    'transparency_dom':      {'preregistration': 0.15, 'protocol_adherence': 0.15,
                              'split_strength': 0.15, 'leakage_risk': 0.15, 'transparency': 0.40},
    'split_dom':             {'preregistration': 0.15, 'protocol_adherence': 0.15,
                              'split_strength': 0.40, 'leakage_risk': 0.15, 'transparency': 0.15},
    'leakage_dom':           {'preregistration': 0.15, 'protocol_adherence': 0.15,
                              'split_strength': 0.15, 'leakage_risk': 0.40, 'transparency': 0.15},
}

# weight key in schemes is 'leakage_risk' but the component value that enters EIS is
# 'leakage_score' (= 1 - risk). Map scheme weight keys -> component-value keys:
WEIGHTKEY_TO_COMPONENT = {
    'preregistration': 'preregistration',
    'protocol_adherence': 'protocol_adherence',
    'split_strength': 'split_strength',
    'leakage_risk': 'leakage_score',
    'transparency': 'transparency',
}


def eis_from_components(comp: dict, scheme: dict) -> float:
    """EIS is a weighted sum of the five component values; the engine computes
    exactly this. Computing it here for alternative schemes is the same formula,
    not a reimplementation (verified against the engine below)."""
    return float(sum(scheme[wk] * comp[WEIGHTKEY_TO_COMPONENT[wk]] for wk in scheme))


def generate_corpus(n: int, seed: int) -> pd.DataFrame:
    """Generate n synthetic protocols with independently-varied underlying features,
    score each via the canonical engine, and return a DataFrame of components + EIS."""
    rng = np.random.default_rng(seed)
    rows = []
    for i in range(n):
        total = int(rng.choice([20, 50, 100, 200, 500]))
        dev_ratio = float(rng.choice([0.5, 0.6, 0.7, 0.8]))
        n_dev = max(1, int(total * dev_ratio))
        n_hold = max(1, total - n_dev)

        # leakage controlled directly via z = (holdout - dev_mean)/dev_std
        dev_mean, dev_std = 0.70, 0.05
        z = float(rng.uniform(-2.0, 2.5))
        holdout_val = float(np.clip(dev_mean + z * dev_std, 0.0, 1.0))

        spec = ProtocolSpec(
            split_completed=bool(rng.random() < 0.90),
            criteria_registered=bool(rng.random() < 0.80),
            development_completed=bool(rng.random() < 0.80),
            validation_completed=bool(rng.random() < 0.85),
            has_regdate_and_hash=bool(rng.random() < 0.60),
            criteria_have_thresholds=bool(rng.random() < 0.70),
            criteria_have_descriptions=bool(rng.random() < 0.60),
            n_development=n_dev,
            n_holdout=n_hold,
            has_integrity_verification=bool(rng.random() < 0.60),
            has_split_date=bool(rng.random() < 0.70),
            has_binding_declaration=bool(rng.random() < 0.60),
            dev_metrics={'f1_score': {'mean': dev_mean, 'std': dev_std, 'min': 0.62,
                                      'values': [0.72, 0.68, 0.70, 0.66, 0.74]}},
            holdout_metrics={'f1_score': holdout_val},
        )
        result = score_protocol(spec)            # CANONICAL engine call
        comp = components_of(result)
        row = {'protocol_id': i, 'eis_default_engine': result['eis']}
        row.update(comp)
        rows.append(row)
    return pd.DataFrame(rows)


def analysis_correlation(df: pd.DataFrame) -> pd.DataFrame:
    """Spearman correlation matrix among the five components."""
    corr = df[COMPONENTS].corr(method='spearman')
    return corr


def analysis_weight_stability(df: pd.DataFrame) -> pd.DataFrame:
    """Recompute EIS under each scheme; Spearman rank-corr of each scheme's ordering
    vs the default ordering. Also verify engine EIS == default-scheme weighted sum."""
    comps = df[COMPONENTS].to_dict('records')

    # verify linearity against the engine for the default scheme
    default_dot = np.array([eis_from_components(c, WEIGHT_SCHEMES['default']) for c in comps])
    engine_eis = df['eis_default_engine'].to_numpy()
    max_abs_diff = float(np.max(np.abs(default_dot - engine_eis)))
    assert max_abs_diff < 1e-9, f"EIS linearity check failed: max diff {max_abs_diff}"

    # EIS under every scheme
    scheme_eis = {name: np.array([eis_from_components(c, w) for c in comps])
                  for name, w in WEIGHT_SCHEMES.items()}

    default_rank_basis = scheme_eis['default']
    out = []
    for name, vals in scheme_eis.items():
        rho, _ = scipy_stats.spearmanr(default_rank_basis, vals)
        out.append({'scheme': name, 'spearman_vs_default': float(rho),
                    'mean_eis': float(np.mean(vals)), 'std_eis': float(np.std(vals))})
    return pd.DataFrame(out), max_abs_diff


def analysis_sanity_monotonicity() -> pd.DataFrame:
    """SECONDARY, circular-by-construction: more dimensions satisfied -> higher EIS."""
    levels = []
    # progressively strengthen the protocol across 6 levels
    configs = [
        dict(split_completed=False, criteria_registered=False, development_completed=False,
             validation_completed=False, has_regdate_and_hash=False, criteria_have_thresholds=False,
             criteria_have_descriptions=False, n_development=10, n_holdout=10,
             has_integrity_verification=False, has_split_date=False, has_binding_declaration=False,
             holdout_metrics={'f1_score': 0.95}),                       # level 0 (worst)
        dict(split_completed=True, criteria_registered=False, development_completed=False,
             validation_completed=False, has_regdate_and_hash=False, criteria_have_thresholds=False,
             criteria_have_descriptions=False, n_development=60, n_holdout=40,
             has_integrity_verification=False, has_split_date=False, has_binding_declaration=False,
             holdout_metrics={'f1_score': 0.90}),                       # level 1
        dict(split_completed=True, criteria_registered=True, development_completed=False,
             validation_completed=False, has_regdate_and_hash=False, criteria_have_thresholds=True,
             criteria_have_descriptions=False, n_development=70, n_holdout=30,
             has_integrity_verification=False, has_split_date=True, has_binding_declaration=False,
             holdout_metrics={'f1_score': 0.80}),                       # level 2
        dict(split_completed=True, criteria_registered=True, development_completed=True,
             validation_completed=False, has_regdate_and_hash=True, criteria_have_thresholds=True,
             criteria_have_descriptions=True, n_development=70, n_holdout=30,
             has_integrity_verification=True, has_split_date=True, has_binding_declaration=False,
             holdout_metrics={'f1_score': 0.72}),                       # level 3
        dict(split_completed=True, criteria_registered=True, development_completed=True,
             validation_completed=True, has_regdate_and_hash=True, criteria_have_thresholds=True,
             criteria_have_descriptions=True, n_development=70, n_holdout=30,
             has_integrity_verification=True, has_split_date=True, has_binding_declaration=True,
             holdout_metrics={'f1_score': 0.68}),                       # level 4
        dict(split_completed=True, criteria_registered=True, development_completed=True,
             validation_completed=True, has_regdate_and_hash=True, criteria_have_thresholds=True,
             criteria_have_descriptions=True, n_development=100, n_holdout=100,
             has_integrity_verification=True, has_split_date=True, has_binding_declaration=True,
             holdout_metrics={'f1_score': 0.66}),                       # level 5 (best)
    ]
    for lvl, cfg in enumerate(configs):
        spec = ProtocolSpec(**cfg)
        r = score_protocol(spec)
        levels.append({'level': lvl, 'eis': r['eis']})
    return pd.DataFrame(levels)


def main():
    root = HERE.parent if (HERE.parent / "engine").exists() else HERE
    out_dir = root / "outputs" / "study1"
    logs_dir = root / "logs"
    out_dir.mkdir(parents=True, exist_ok=True)
    logs_dir.mkdir(parents=True, exist_ok=True)

    N = 300
    print("=" * 70)
    print("STUDY 1 — EIS INTERNAL COHERENCE & WEIGHT STABILITY (COH)")
    print("Internal construct check. NOT external validation.")
    print("=" * 70)
    print(f"Master seed: {MASTER_SEED} | corpus size: {N}")

    # --- generate corpus via canonical engine ---
    df = generate_corpus(N, MASTER_SEED)
    df.to_csv(out_dir / "study1_corpus.csv", index=False)
    print(f"\nCorpus scored via canonical engine -> {out_dir / 'study1_corpus.csv'}")
    print("\nComponent descriptive statistics:")
    print(df[COMPONENTS].describe().round(4).to_string())

    # --- analysis 1: non-redundancy ---
    corr = analysis_correlation(df)
    corr.to_csv(out_dir / "component_correlation_matrix.csv")
    off_diag = corr.where(~np.eye(len(corr), dtype=bool))
    max_abs_corr = float(np.nanmax(np.abs(off_diag.to_numpy())))
    mean_abs_corr = float(np.nanmean(np.abs(off_diag.to_numpy())))
    print("\n[1] DIMENSIONAL NON-REDUNDANCY (Spearman):")
    print(corr.round(3).to_string())
    print(f"    max |off-diagonal corr| = {max_abs_corr:.3f}")
    print(f"    mean |off-diagonal corr| = {mean_abs_corr:.3f}")

    # --- analysis 2: weight stability ---
    ws, linearity_diff = analysis_weight_stability(df)
    ws.to_csv(out_dir / "weight_stability.csv", index=False)
    alt = ws[ws['scheme'] != 'default']
    min_rho = float(alt['spearman_vs_default'].min())
    mean_rho = float(alt['spearman_vs_default'].mean())
    print("\n[2] WEIGHT STABILITY (Spearman rank-corr vs default ordering):")
    print(ws.round(4).to_string(index=False))
    print(f"    engine-vs-formula linearity check: max diff {linearity_diff:.2e} (must be ~0)")
    print(f"    min rank-corr across alt schemes  = {min_rho:.4f}")
    print(f"    mean rank-corr across alt schemes = {mean_rho:.4f}")

    # --- analysis 3: sanity monotonicity (circular by construction) ---
    sanity = analysis_sanity_monotonicity()
    sanity.to_csv(out_dir / "sanity_monotonicity.csv", index=False)
    is_monotonic = bool(np.all(np.diff(sanity['eis'].to_numpy()) > 0))
    print("\n[3] SYNTHETIC MONOTONICITY SANITY CHECK (circular by construction):")
    print(sanity.round(4).to_string(index=False))
    print(f"    strictly increasing: {is_monotonic}  (expected True; sanity only, NOT validity)")

    # --- summary + log ---
    summary = {
        'study': 'Study 1 — EIS internal coherence & weight stability (COH)',
        'interpretation': 'internal construct check; NOT external validation',
        'master_seed': MASTER_SEED,
        'corpus_size': N,
        'non_redundancy': {
            'max_abs_offdiag_spearman': max_abs_corr,
            'mean_abs_offdiag_spearman': mean_abs_corr,
        },
        'weight_stability': {
            'min_rank_corr_vs_default': min_rho,
            'mean_rank_corr_vs_default': mean_rho,
            'linearity_check_max_diff': linearity_diff,
        },
        'sanity_monotonicity': {'strictly_increasing': is_monotonic},
        'timestamp': datetime.now().isoformat(),
    }
    with open(out_dir / "study1_summary.json", 'w', encoding='utf-8') as f:
        json.dump(summary, f, indent=2)

    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    log = {**summary,
           'python_version': sys.version.split()[0],
           'platform': platform.platform(),
           'numpy': np.__version__, 'pandas': pd.__version__, 'scipy': scipy_stats.__name__}
    with open(logs_dir / f"study1_run_{ts}.json", 'w', encoding='utf-8') as f:
        json.dump(log, f, indent=2)

    print(f"\nOutputs -> {out_dir}")
    print(f"Log     -> {logs_dir / f'study1_run_{ts}.json'}")
    print("\nNOTE: internal coherence only. External evidence rests on Study 4.")
    print("=" * 70)


if __name__ == "__main__":
    main()